<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="2019.10.30" name="platformPack_tilesheet" tilewidth="64" tileheight="64" tilecount="98" columns="14">
 <image source="public/images/platformPack_tilesheet.png" trans="ffffff" width="896" height="448"/>
 <tile id="0" type="obstacle"/>
 <tile id="1" type="obstacle"/>
 <tile id="2" type="obstacle"/>
 <tile id="3" type="obstacle"/>
 <tile id="4" type="obstacle"/>
 <tile id="6" type="obstacle"/>
 <tile id="7" type="obstacle"/>
 <tile id="10" type="enemy"/>
 <tile id="11" type="enemy"/>
 <tile id="14" type="obstacle"/>
 <tile id="15" type="obstacle"/>
 <tile id="16" type="obstacle"/>
 <tile id="17" type="obstacle"/>
 <tile id="18" type="obstacle"/>
 <tile id="19" type="obstacle"/>
 <tile id="20" type="obstacle"/>
 <tile id="21" type="obstacle"/>
 <tile id="24" type="enemy"/>
 <tile id="25" type="enemy"/>
 <tile id="28" type="obstacle"/>
 <tile id="29" type="obstacle"/>
 <tile id="30" type="obstacle"/>
 <tile id="31" type="obstacle"/>
 <tile id="32" type="obstacle"/>
 <tile id="42" type="obstacle"/>
 <tile id="43" type="obstacle"/>
 <tile id="44" type="obstacle"/>
 <tile id="45" type="obstacle"/>
 <tile id="46" type="obstacle"/>
 <tile id="59" type="obstacle"/>
 <tile id="60" type="obstacle"/>
 <tile id="73" type="obstacle"/>
 <tile id="74" type="obstacle"/>
 <tile id="75" type="door"/>
 <tile id="76" type="door"/>
 <tile id="77" type="door"/>
 <tile id="78" type="door"/>
 <tile id="79" type="door"/>
 <tile id="89" type="door"/>
 <tile id="90" type="door"/>
 <tile id="91" type="door"/>
 <tile id="92" type="door"/>
 <tile id="93" type="door"/>
 <tile id="95" type="start_point"/>
</tileset>
